### PR TITLE
B2: Swagger Endpoints (Post, Get, Put, Delete), Epic: Add Announcements 

### LINKED ISSUE #25: Issue B2: Backend Controller for CRUD operations for announcements
Developer Story:

As an developer
I have access to backend endpoints (through swagger) for CRUD operations for the Announcements table
So that I can build future features using this table
Acceptance Criteria:

 The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
 The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
 There is a GET endpoint to get all announcements for a specified commons
 There is a GET endpoint to get an announcement by its individual id number
 There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoint.
 There is a DELETE endpoint that allows deleting an announcement

### PR DESCRIPTION
**Pull request by chrisriney4**
## Overview

In this PR, 

# Issue B2: Backend Controller for CRUD operations for announcements
- [x] There is a POST endpoint to post a new announcement
- [x] The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
- [x] The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
- [x] There is a GET endpoint to get all announcements for a specified commons
- [x] There is a GET endpoint to get an announcement by its individual id number
- [x] There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoint.
- [x] There is a DELETE endpoint that allows deleting an announcement

## Screenshots
image
image
image
image
image
image
image
image

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #25

### CODE REVIEW

**Review by jtanggy — APPROVED** [review]
LGTM

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Review by sangitakunapuli — DISMISSED** [review]
please update the PR description to describe what this PR achieves, including screenshots or a deployment link

**Review by jinanthony — APPROVED** [review]
LGTM!

**Review by AnikaArora — APPROVED** [review]
LGTM!

**Comment by alexanderthomasucsb** [comment]
LGTM

**Pull request merged**
