### PR TITLE
AJ -- fix typo in gamePlay.md

### PR DESCRIPTION
**Pull request by jinanthony**
## Overview
CowHeath is a misspelling of CowHealth

### CODE REVIEW

**Review by sangitakunapuli — APPROVED** [review]
LGTM - please pull main into this branch before merge to update this PR

**Comment by TianyiYang-Tyler** [comment]
LGTM

**Review by TianyiYang-Tyler — APPROVED** [review]
LGTM

**Comment by jinanthony** [comment]
Reopen to fix lint expected check

**Pull request merged**
